config/routes.rb
Rails.application.routes.draw do
  resources :members
  get  'search'          => 'members#search'

  root to: 'members#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
	def self.ethnic()
		et = ['Asian',
		'Indian',
		'African Americans',
		'Asian Americans',
		'European',
		'British',
		'Jewish',
		'Latino',
		'Native American',
		'Arabic']
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  require 'json'
  require 'open-uri'
  protect_from_forgery with: :exception

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :hits
  require 'json'
  require 'open-uri'

  # GET /members
  # GET /members.json
  def index
   
    @ethnic = Member.ethnic
    # @members = []
    # members.each do |member|
    #   attributes = member.except("id")
    #   @members <<  Member.create(attributes)
    # end

  if params[:vegan].present?

    @members = Member.where(is_veg: true).order(:id).page(params[:page]) 
  elsif params[:type].present?
    @members = Member.where(ethnicity: params[:type]).order(:id).page(params[:page])
  else  
    @members = Member.order(:id).page(params[:page])

  end 
    
  end

  def search
    query, page = params[:query].try(:downcase), params[:page] || 1


    @members = Member.all.where('lower(status) like ?', "%#{query}%")
   
                                  
    
                                                               

  end


  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def hits
      url = 'https://idfy.0x10.info/api/idfy-status?type=json&query=api_hits'
      data = JSON.load(open(url))
      @hits = data['api_hits']
      
    end
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:status, :ethnicity, :weight, :height,  :vegan, :is_veg, :drink, :dob, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackEarth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_area :status %>
  </div>
  <div class="field">
    <%= f.label :ethnicity %><br>
    <%= f.number_field :ethnicity %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :is_veg %><br>
    <%= f.check_box :is_veg %>
  </div>
  <div class="field">
    <%= f.label :drink %><br>
    <%= f.check_box :drink %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<div class="post">
<div class="panel panel-default">
              <div class="panel-body">
                <div class="row">
                  <div class="col-md-3"><%= image_tag(member.image)%></div>
                  <div class="col-md-9">
                    <div class="row">
                      <div class="col-md-12"><%= Member.ethnic[member.ethnicity]%></div>
                    </div>
                     <div class="row">
                       <div class="col-md-12"><%= member.status%></div>
                     </div> 

                  </div>

                </div>
                <div class="row">
                  <div class="col-md-12">
                    drink: <%= member.drink%>|vegan: <%= member.is_veg%>| height: <%= member.height%> cm|weight: <%= (member.weight/1000.0).round(2) %> KG ------ <%= link_to 'Show', member %>

                  </div>  

                </div>
              
              </div>

          </div>
</div>          

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-6">
    <%= form_tag search_path, method: :get do %>
      <%= text_field_tag :query, params[:query], placeholder: 'Search status '%>
    <% end -%>
</div>    
<div class="col-md-6">
  <%= button_to "List Vegan", members_path, :method => :get, name: 'vegan' , value: "vegan" %>
</div>
</div>  


<div class="posts">
    <div class="row">
       <div id="sidebar" class="col-md-2">
          <b>Ethnicity</b>
          <br>
         <% @ethnic.each_with_index do |ethnic, index| %>
          
          <%= link_to ethnic, members_path(:type => index) %>
          <br>
         <% end %>

         <b>API HITS: </b><%=@hits%>
       </div>
      
       <div id="content" class="col-md-10">
       <div class="page">
        <%= render @members %>
       </div> 
       </div>

    </div>
    


</div>
<%= paginate @members %>

app/views/members/index.js.erb
$(".posts").append("<%= escape_javascript(render(@members)) %>");

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/search.html.erb
<%= render @members %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @member.status %>
</p>

<p>
  <strong>Ethnicity:</strong>
  <%= @member.ethnicity %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @member.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @member.height %>
</p>

<p>
  <strong>Is veg:</strong>
  <%= @member.is_veg %>
</p>

<p>
  <strong>Drink:</strong>
  <%= @member.drink %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @member.dob %>
</p>

<p>
  <strong>Image:</strong>
  <%= @member.image %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>